version = 1

SPDX-PackageName = "opendatahub-ui-components"
SPDX-PackageSupplier = "NOI Techpark <digital@noi.bz.it>"
SPDX-PackageDownloadLocation = "https://github.com/noi-techpark/opendatahub-ui-components"

[[annotations]]
path = [".github/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"
